### PR TITLE
Extend the changelog to most of the languages

### PR DESCRIPTION
**Pull request by andreaTP**
Still missing Go and Java:

 - Java: not necessary to include it in the package
 - Go: we would need to commit the changelog file to this repo
 
 Given this nuance with Go (I haven't thought about it earlier :cry: ) I'm reconsidering committing the changelog file ...
 Happy to hear thoughts @ricardoboss @baywet

### CODE REVIEW

**Review by baywet — APPROVED** [review]

**Comment by ricardoboss** [comment]
I have absolutely no experience with Go... Do they really require you to check in a CHANGELOG.md file for it to be included?
Is the CHANGELOG for go packages shown somewhere?

**Comment by andreaTP** [comment]
Good question @ricardoboss , seems like there is no specific handling of the changelog in Go packages, [e.g.](https://pkg.go.dev/github.com/git-chglog/git-chglog#section-readme).

Leaving it out for the time being.

**Comment by baywet** [comment]
Go handles everything in doc comments and in the readme... which is constraining.
For kiota/microsoft graph, we maintain markdown changelogs as this is a common practice on GitHub anyway. And we didn't bother "translating" the changelog as doc comments for the package.

**Comment by andreaTP** [comment]
@ricardoboss , @baywet this is so ironic I cannot hold:
https://github.com/std-uritemplate/std-uritemplate/actions/runs/10074545375

C# and Dart releases failed XD, let me see how to fix it ...

**Pull request merged**
