### PR TITLE
[chore] Minor Readme updates

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Review by baywet — APPROVED** [review]

**Comment by andreaTP** [comment]
Now that I notice, this is unexpected:
Screenshot from 2024-05-09 14-13-44

We separated the repo to avoid having the CLA checks here, @ChrisSfanos , can you check what's going on here?

**Comment by ChrisSfanos** [comment]
I will see if it can be filtered at the repo and not organization level

**Comment by ChrisSfanos** [comment]
https://github.com/microsoft/.github/blob/main/policies/cla.yml

You can configure the CLA via the cla.yml file (example from MSFT)

**Comment by andreaTP** [comment]
Do we have documentation about all the possible options?

@baywet do you mind having a look yourself or someone in your team?

**Comment by andreaTP** [comment]
The least desirable option is to remove the CLA check from the checks required to merge in this repo.

**Comment by baywet** [comment]
@andreaTP I'm not familiar with that infrastructure, this is owned by a dedicated team internally.
But I believe this line is what makes it ignore some repos. https://github.com/microsoft/.github/blob/adf09b6d51b8fe39df9fca126e8d45c6a0e59820/policies/cla.yml#L7

**Comment by baywet** [comment]
Yep, that did it, see those
- https://github.com/std-uritemplate/.github/pull/5
- https://github.com/std-uritemplate/std-uritemplate-csharp/pull/5
- https://github.com/std-uritemplate/std-uritemplate/pull/180

**Comment by andreaTP** [comment]
Thanks @baywet :tada: appreciated!

**Pull request merged**
