### PR TITLE
Run tests in Go without additional dependencies

### PR DESCRIPTION
**Pull request by andreaTP**
Suggested by @lburgazzoli

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
I don't have any strong objection to this approach. The reason why I brought on assert was because I assumed we'd be writing additional tests over time and it'd be worth it.

What I don't understand is that when you go get/build the package, the import moves from indirect to direct.
Also the mod file needs to be updated with that change

**Comment by andreaTP** [comment]
I leave this to @lburgazzoli 🙏

**Comment by lburgazzoli** [comment]
I think it is important to understand what the goal of "zero dependencies" is, so 

1. if you really wants to be sure that no other packages are downloaded when including std-uritemplate, then a solution like the one proposed here by @andreaTP is a reasonable one. 
2. if the goal is that no 3rd party dependencies are included as part of the build, I think this can be achieved in a different way, so as example by having a proper `go.mod` file here (which can be done by run `go mod tidy` and that then would include the `testify` lib) should do the trick as no `testify` would then be part of the consumer of the lib.

About point 2, this can be simulated by making a proper `go.mod` and then executing the test suite which then would produce a `go.mod` like:

```             
module stduritemplate

go 1.21.4

replace github.com/std-uritemplate/std-uritemplate/go => ../
require github.com/std-uritemplate/std-uritemplate/go v0.0.0-00010101000000-000000000000
```

so, no `testify` which is also confirmed by `go list`

```json
{
        "Dir": "/Users/luca-rh/work/dev/std-uritemplate/go/test",
        "ImportPath": "stduritemplate",
        "Name": "main",
        "Target": "/Users/luca-rh/.cache/go/bin/stduritemplate",
        "Root": "/Users/luca-rh/work/dev/std-uritemplate/go/test",
        "Module": {
                "Path": "stduritemplate",
                "Main": true,
                "Dir": "/Users/luca-rh/work/dev/std-uritemplate/go/test",
                "GoMod": "/Users/luca-rh/work/dev/std-uritemplate/go/test/go.mod",
                "GoVersion": "1.21.4"
        },
        "Match": [
                "."
        ],
        "Stale": true,
        "StaleReason": "not installed but available in build cache",
        "GoFiles": [
                "test.go"
        ],
        "Imports": [
                "encoding/json",
                "fmt",
                "github.com/std-uritemplate/std-uritemplate/go",
                "os",
                "strings",
                "time"
        ],
        "Deps": [
                "bytes",
                "encoding",
                "encoding/base64",
                "encoding/binary",
                "encoding/json",
                "errors",
                "fmt",
                "github.com/std-uritemplate/std-uritemplate/go",
                "internal/abi",
                "internal/bytealg",
                "internal/coverage/rtcov",
                "internal/cpu",
                "internal/fmtsort",
                "internal/goarch",
                "internal/godebugs",
                "internal/goexperiment",
                "internal/goos",
                "internal/itoa",
                "internal/oserror",
                "internal/poll",
                "internal/race",
                "internal/reflectlite",
                "internal/safefilepath",
                "internal/syscall/execenv",
                "internal/syscall/unix",
                "internal/testlog",
                "internal/unsafeheader",
                "io",
                "io/fs",
                "math",
                "math/bits",
                "net/url",
                "os",
                "path",
                "reflect",
                "runtime",
                "runtime/internal/atomic",
                "runtime/internal/math",
                "runtime/internal/sys",
                "sort",
                "strconv",
                "strings",
                "sync",
                "sync/atomic",
                "syscall",
                "time",
                "unicode",
                "unicode/utf16",
                "unicode/utf8",
                "unsafe"
        ]
}
```

However, testify would appear in the `go.sum`package as the go tool-chain must ensure the packages you have downloaded on disk are exactly what they are supposed to be.

**Comment by baywet** [comment]
thanks for chiming in @lburgazzoli 
I'll try to recap the goal generically as I understand it so it applies to other languages as well.
"a canonical, high performance, zero additional *runtime* dependency implementation of RFC6570"
Personally, I'm fine having additional *dev* dependencies if that allows us to reduce the maintenance burden in the code base. So long as they are not in use at runtime by applications that depend on the library.

Now, my understanding of how go manages dependencies, which might be wrong, was that any direct *runtime required* dependency would be listed in the main section of the go mod. Any transitive or test dependency, would be listed as indirect. Is that not the case?

**Comment by lburgazzoli** [comment]
> thanks for chiming in @lburgazzoli I'll try to recap the goal generically as I understand it so it applies to other languages as well. "a canonical, high performance, zero additional _runtime_ dependency implementation of RFC6570" Personally, I'm fine having additional _dev_ dependencies if that allows us to reduce the maintenance burden in the code base. So long as they are not in use at runtime by applications that depend on the library.
> 

as long as none of the  function/constant/etc defined in `_test.go` is referenced in non test files, then any additional dependency should not be automatically not included at runtime. Things are a little bit [tricky](https://www.dolthub.com/blog/2022-11-07-pruning-test-dependencies-from-golang-binaries/) in some case but that usually depends on a bad code/modules organization 

> Now, my understanding of how go manages dependencies, which might be wrong, was that any direct _runtime required_ dependency would be listed in the main section of the go mod. Any transitive or test dependency, would be listed as indirect. Is that not the case?

I think this was probably true in older version of go but since the introduction of [module graph pruning](https://go.dev/ref/mod#graph-pruning) in go 1.17, that should not be more the case. But even if it was, then the previous point still apply so, no test bits should be in the runtime.

**Comment by baywet** [comment]
Thanks for the additional information here.
So if I understand things correctly, besides making the test file has the right suffix, no action is required?

**Comment by lburgazzoli** [comment]
And tidy the `go.mod` file (go mod tidy) so the testify deps is added and any consumer won't require go to artificially make it.

**Comment by andreaTP** [comment]
> I can do a PR and run some examples against my branch to see if my explanation is actually correct

please 🙏

**Pull request closed without merging**
